# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: 
      - main
      - alek-memento-workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Set up flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          # The Flutter build release channel
          channel: stable
          # Cache the Flutter SDK
          cache:  false
    
      - name: Install dependencies
        run: flutter pub get
      
      - name: Enable Windows Desktop Supports 
        run: flutter config --enable-windows-desktop
      
      - name: Build Windows executable
        run: flutter build windows --release
      
      - name:  Upload artifact (exe)
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build\windows\x64\runner\Release\vigenere_encryption.exe

          
      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      # - name: Analyze project source
      #   run: dart analyze

      # # Your project will need to have tests in test/ and a dependency on
      # # package:test for this step to succeed. Note that Flutter projects will
      # # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: dart test
